apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: u0v3w1yjt-java-springboot
  janus-idp.io/tekton: u0v3w1yjt-java-springboot
  backstage.io/kubernetes-id: u0v3w1yjt-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u0v3w1yjt-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
